Update code to avoid use of DEPRECATED Mojolicious methods
jhthorsen/mojolicious-plugin-assetpack pull request #142
Opened 2020-12-09 19:26 UTC by zoffixznet

Fixes warnings issued by latest Mojolicious.

Passes `TEST_ONLINE=1 make test`

Note: `t/mount.t` still has deprecation warnings about `->detour` used in that test file. I'm unsure how to fix it. I tried `$t->app->routes->any('/mounted' => {app => $app});` on that line, but test failed.

2020-12-10 00:42 UTC, jhthorsen requested changes
I think we have detect which version of Mojolicious we have and support both old and new syntax. I guess we can detect it by doing `$route->can('methods')`, since "any" is already there.

2020-12-10 19:30 UTC, zoffixznet commented
Done for `methods`

I flipped through Mojolicious on metacpan and `any` existed [since at least `3.45`](https://metacpan.org/pod/release/SRI/Mojolicious-3.45/lib/Mojolicious/Routes/Route.pm#any), so should be OK to assume users have it.

2020-12-11 00:40 UTC, zoffixznet commented
I pushed another update. Passes `TEST_ONLINE=1 make test`. From [the docs](https://metacpan.org/pod/Mojolicious::Routes::Route#any) it appears we don't need to do any `->can`s and can just use the short form.


In case we can't, this is the code with `->can` that I had:

```perl
has route => sub {
  my $route = shift->_app->routes->any('/asset/:checksum/*name');
  my $methods = $route->can('methods') || 'via'; # support for Mojolicious <8.67
  $route->$methods(qw(HEAD GET))->name('assetpack')->to(cb => \&_serve);
};
```

2020-12-11 02:15 UTC, jhthorsen approved these changes
Looks great!

2020-12-11 02:15 UTC, merged